In [76]:
from numpy import*
from sympy import*


In [46]:
#Declarando as matrizes 
A = array([[1,1],[-3,1]])
B = array([[6],[2]])


In [47]:
#Encontrar a inversa de A
A_inv = linalg.inv(A)
A_inv

array([[ 0.25, -0.25],
       [ 0.75,  0.25]])

In [48]:
#Encontrar X  pela inversa de A
X = dot(A_inv,B)
X 

array([[1.],
       [5.]])

In [50]:
#Encontrar X usando o Solve 
X = linalg.solve(A,B)
X

array([[1.],
       [5.]])

# Resolva o sistema

# x + y + z = 1

# 4x + 4y + 2z = 2

# 2x + y - z = 0 

In [55]:
# Declarar as matrizes 

A = array([[1,1,1],[4,4,2],[2,1,-1]])
B = array([[1],[2],[0]])

In [57]:
result = linalg.solve(A,B)
result # x = 1 , y= -1 e z = 1

array([[ 1.],
       [-1.],
       [ 1.]])

In [91]:
#Calcule a inversa da matriz A :
a,b,c,d = symbols("a b c d ")

In [92]:
A = Matrix([[a, b],[c, d]])
A


Matrix([
[a, b],
[c, d]])

In [93]:
A.inv()

Matrix([
[ d/(a*d - b*c), -b/(a*d - b*c)],
[-c/(a*d - b*c),  a/(a*d - b*c)]])